-- Intentionally empty.
--
-- Demo tenant/users/catalogue data must not be inserted automatically by the
-- production migration path. For local development, apply
-- schema/postgres/seeds/dev_seed.sql explicitly after running migrations.
